version: '3.7'

services:
  gemini_ai:
    build:
      context: ./gemini_ai
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - FLASK_ENV=development
      - GEMINI_API_KEY=${GEMINI_API_KEY}

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - gemini_ai
